# Generated by Django 6.0.5 on 2026-05-07 22:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ban_reason',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lookup_type',
            },
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('changed_from', models.JSONField(blank=True, null=True)),
                ('word', models.CharField(max_length=100, unique=True)),
                ('note', models.TextField(blank=True)),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_words', to='generator.banreason')),
            ],
            options={
                'db_table': 'banned_word',
            },
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('vowels', models.CharField(blank=True, help_text="Vokalanker für Silbenprüfung, z.B. 'aeiouäöüy' für Deutsch", max_length=50)),
                ('extra_vowels', models.CharField(blank=True, max_length=50)),
                ('pyphen_lang', models.CharField(blank=True, help_text='Pyphen-Sprachcode, z.B. de_DE, en_US', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lookups', to='generator.lookuptype')),
            ],
            options={
                'db_table': 'lookup',
                'ordering': ['type', 'sort_order', 'label'],
                'unique_together': {('type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('changed_from', models.JSONField(blank=True, null=True)),
                ('word', models.CharField(max_length=100)),
                ('word_length', models.PositiveSmallIntegerField(editable=False)),
                ('syllable_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('syllables', models.JSONField(blank=True, default=list)),
                ('syllable_shuffle_mode', models.CharField(choices=[('unsuitable', 'Nicht geeignet'), ('rotate', 'Rotation'), ('random', 'Zufällig'), ('reverse', 'Umgekehrt')], default='unsuitable', max_length=20)),
                ('phonetic_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_compound', models.BooleanField(default=False)),
                ('is_loanword', models.BooleanField(default=False)),
                ('is_germanized', models.BooleanField(default=False, help_text='z.B. Computer, Meeting')),
                ('is_technical', models.BooleanField(default=False)),
                ('reverse_suitable', models.BooleanField(default=True)),
                ('syllables_anchored', models.BooleanField(default=True)),
                ('difficulty', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'difficulty'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words_by_difficulty', to='generator.lookup')),
                ('origin', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'origin'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words_by_origin', to='generator.lookup')),
                ('part_of_speech', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'part_of_speech'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words_by_pos', to='generator.lookup')),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.category')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.word')),
            ],
            options={
                'db_table': 'word_category',
                'unique_together': {('word', 'category')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='words', through='generator.WordCategory', to='generator.category'),
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(limit_choices_to={'type__code': 'language'}, on_delete=django.db.models.deletion.PROTECT, related_name='wordlists_by_language', to='generator.lookup')),
                ('theme', models.ForeignKey(limit_choices_to={'type__code': 'wordlist_theme'}, on_delete=django.db.models.deletion.PROTECT, related_name='wordlists_by_theme', to='generator.lookup')),
            ],
            options={
                'db_table': 'wordlist',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='wordlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='generator.wordlist'),
        ),
        migrations.CreateModel(
            name='GeneratorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100)),
                ('changed_from', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('word_count', models.PositiveSmallIntegerField(default=4)),
                ('min_length', models.PositiveSmallIntegerField(default=4)),
                ('max_length', models.PositiveSmallIntegerField(default=30)),
                ('separator', models.CharField(blank=True, default='-', max_length=10)),
                ('special_chars_enabled', models.BooleanField(default=False)),
                ('avoid_same_initial', models.BooleanField(default=False)),
                ('exclude_germanized', models.BooleanField(default=True)),
                ('case_mode', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'case_mode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_case', to='generator.lookup')),
                ('difficulty', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'difficulty'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_difficulty', to='generator.lookup')),
                ('eszett_mode', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'eszett_mode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_eszett', to='generator.lookup')),
                ('reverse_mode', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'reverse_mode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_reverse', to='generator.lookup')),
                ('umlaut_mode', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'umlaut_mode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_by_umlaut', to='generator.lookup')),
                ('wordlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='generator.wordlist')),
            ],
            options={
                'db_table': 'generator_profile',
            },
        ),
        migrations.CreateModel(
            name='SpecialCharRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_char', models.CharField(max_length=1)),
                ('target_char', models.CharField(max_length=2)),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='1–10, höher = wahrscheinlicher')),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_char_rules', to='generator.generatorprofile')),
            ],
            options={
                'db_table': 'special_char_rule',
                'constraints': [models.CheckConstraint(condition=models.Q(('weight__gte', 1), ('weight__lte', 10)), name='special_char_weight_range')],
                'unique_together': {('profile', 'source_char', 'target_char')},
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['wordlist', 'word_length'], name='word_wordlis_5da1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['wordlist', 'is_germanized'], name='word_wordlis_b75829_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['wordlist', 'syllable_count'], name='word_wordlis_313b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['wordlist', 'syllables_anchored'], name='word_wordlis_0bef84_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(condition=models.Q(('word_length__gte', 1)), name='word_length_positive'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phonetic_score__gte', 1), ('phonetic_score__lte', 10)), ('phonetic_score__isnull', True), _connector='OR'), name='phonetic_score_range'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('wordlist', 'word')},
        ),
        migrations.AddConstraint(
            model_name='generatorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('word_count__gte', 1), ('word_count__lte', 20)), name='word_count_range'),
        ),
        migrations.AddConstraint(
            model_name='generatorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('min_length__lte', models.F('max_length'))), name='min_length_lte_max_length'),
        ),
    ]
