# Generated by Django 6.0.5 on 2026-05-08 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_lookup_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_feel_diff', models.PositiveSmallIntegerField(choices=[(1, 'sehr gut merkbar'), (2, 'gut merkbar'), (3, 'mittel'), (4, 'schwer merkbar'), (5, 'nicht verwendbar')], help_text='Subjektive Schwierigkeitseinschätzung (1=sehr gut merkbar, 5=nicht verwendbar)')),
                ('note', models.CharField(blank=True, help_text='Optionale Freitextnotiz des Nutzers', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='generator.word')),
            ],
            options={
                'db_table': 'user_word_feedback',
                'indexes': [models.Index(fields=['user', 'user_feel_diff'], name='user_word_f_user_id_7b9787_idx'), models.Index(fields=['word', 'user_feel_diff'], name='user_word_f_word_id_2bb499_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user_feel_diff__gte', 1), ('user_feel_diff__lte', 5)), name='user_feel_diff_range')],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
